sudo: required
services:
- docker
language: node_js
node_js:
- '8'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GH_REPO=qcif/sails-hook-eresearch-customisations
  - GIT_NAME=DeploymentBot
  - GIT_EMAIL=deploy@travis-ci.org
  - secure: FKadcgd6sOju0vTWXOddalHSDid/P/+iw2dhYrmJ/ePLYPL1IrIkW4e4SAqGzDk8PE1yY9Pgzi8qODhHIpC486B50DZtkF+bneKuKyil+SBTPJ7DKa7cSa2BWGsGQsT8+ZPF6XTl/ybNcvDZkLtH9wVU9zqXL9a5yqkFh+Sa2CMqjZc599oO14WFwzxqEPhbqIWy/rPuFSXA7gId8eJJgF9HKHS30FBVrq430O+XqZJYIyGPfCXhsRAxpbuVnZQsrEHLfYMAKhC7tUB41OuM460YAr5yt+2BWocy9GnTrFcBgfsOq7KgmEQ+QnHjWpqkpJA68eX7Ea36b0H5LLRLag9qL7P6a4eBfCY2DUS9NchU0s7NuIbx86gGYWvqDG3AyT2OCRNbFaPcP1GPb0DeB4PpYm1CLDwq2QRgD5pqXqixFUhqyPmSeMwYknZIIdThwzXCfCin4Phz4Fv3LNVbyC+jkW1WYI/1aLskR6dA9rF/5V1TGaD7L5B47xhmlPRxJtEPzOocn8Ra/gDF8t0NKafkrOtnS8sV78IEt9SiRVSKLEe4IpJ/81B5FdWaSjEE0Kp+GjqAHABk8qAJJOBABPjyo4SKtUpYFZmWHusfkWvlUqG1vM8D1DqAElJHiqT6ug3An/G9mFHWGE4bOUsRdWMhNDmNWmfiGrUiWkqUoT0=
install:
- npm install
script: true
after_success:
- chmod +x deploySnapshotToBranch.sh; ./deploySnapshotToBranch.sh
